[dependencies.clap]
default-features = false
features = ["std"]
optional = true
package = "clap"
version = "*"

[dependencies.santiago]
default-features = false
features = ["crate_regex"]
package = "santiago"
version = "*"

[features]
default = ["clap"]

[package]
authors = ["Kevin Amado <kamadorueda@gmail.com>"]
categories = []
description = ""
edition = "2021"
keywords = []
license = "AGPL-3.0-only"
name = "nixel"
repository = "https://github.com/kamadorueda/nixel"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
